# Generated by Django 6.0.3 on 2026-07-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='diseas',
            new_name='disease',
        ),
    ]
